const flagMap: Record<string, string> = {
  argentina: '🇦🇷', brasil: '🇧🇷', brazil: '🇧🇷',
  francia: '🇫🇷', france: '🇫🇷',
  alemania: '🇩🇪', germany: '🇩🇪',
  inglaterra: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', england: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  españa: '🇪🇸', spain: '🇪🇸',
  italia: '🇮🇹', italy: '🇮🇹',
  'paises bajos': '🇳🇱', netherlands: '🇳🇱', holland: '🇳🇱',
  portugal: '🇵🇹',
  belgica: '🇧🇪', belgium: '🇧🇪',
  croacia: '🇭🇷', croatia: '🇭🇷',
  dinamarca: '🇩🇰', denmark: '🇩🇰',
  suiza: '🇨🇭', switzerland: '🇨🇭',
  uruguay: '🇺🇾',
  colombia: '🇨🇴',
  japon: '🇯🇵', japan: '🇯🇵',
  'corea del sur': '🇰🇷', 'south korea': '🇰🇷',
  'arabia saudita': '🇸🇦', 'saudi arabia': '🇸🇦',
  iran: '🇮🇷',
  australia: '🇦🇺',
  canada: '🇨🇦',
  mexico: '🇲🇽',
  'estados unidos': '🇺🇸', usa: '🇺🇸', 'united states': '🇺🇸',
  'costa rica': '🇨🇷',
  marruecos: '🇲🇦', morocco: '🇲🇦',
  senegal: '🇸🇳',
  ghana: '🇬🇭',
  camerun: '🇨🇲', cameroon: '🇨🇲',
  tunez: '🇹🇳', tunisia: '🇹🇳',
  nigeria: '🇳🇬',
  polonia: '🇵🇱', poland: '🇵🇱',
  suecia: '🇸🇪', sweden: '🇸🇪',
  serbia: '🇷🇸',
  ucrania: '🇺🇦', ukraine: '🇺🇦',
  'republica checa': '🇨🇿', 'czech republic': '🇨🇿',
  hungria: '🇭🇺', hungary: '🇭🇺',
  austria: '🇦🇹',
  escocia: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  gales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'nueva zelanda': '🇳🇿', 'new zealand': '🇳🇿',
  peru: '🇵🇪',
  chile: '🇨🇱',
  ecuador: '🇪🇨',
  paraguay: '🇵🇾',
  bolivia: '🇧🇴',
  venezuela: '🇻🇪',
  'sudafrica': '🇿🇦', 'south africa': '🇿🇦',
  egipto: '🇪🇬', egypt: '🇪🇬',
  'costa de marfil': '🇨🇮', 'ivory coast': '🇨🇮',
  argelia: '🇩🇿', algeria: '🇩🇿',
  mali: '🇲🇱',
  angola: '🇦🇴',
  eslovaquia: '🇸🇰', slovakia: '🇸🇰',
  eslovenia: '🇸🇮', slovenia: '🇸🇮',
  rumania: '🇷🇴',
  bulgaria: '🇧🇬',
  grecia: '🇬🇷', greece: '🇬🇷',
  turquia: '🇹🇷', turkey: '🇹🇷',
  israel: '🇮🇱',
  rusia: '🇷🇺', russia: '🇷🇺',
  bosnia: '🇧🇦',
  montenegro: '🇲🇪',
  albania: '🇦🇱',
  islandia: '🇮🇸', iceland: '🇮🇸',
  irlanda: '🇮🇪', ireland: '🇮🇪',
  finlandia: '🇫🇮', finland: '🇫🇮',
  noruega: '🇳🇴', norway: '🇳🇴',
  letonia: '🇱🇻', latvia: '🇱🇻',
  lituania: '🇱🇹', lithuania: '🇱🇹',
  estonia: '🇪🇪',
  catar: '🇶🇦', qatar: '🇶🇦',
  irak: '🇮🇶', iraq: '🇮🇶',
  china: '🇨🇳',
  india: '🇮🇳',
  'corea del norte': '🇰🇵', 'north korea': '🇰🇵',
  tailandia: '🇹🇭', thailand: '🇹🇭',
  vietnam: '🇻🇳',
  indonesia: '🇮🇩',
};

export function getFlag(name: string): string {
  if (!name) return '';
  const key = name.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  return flagMap[key] || '';
}
