[toolchain]
anchor_version = "1.0.0"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
settlement = "EzZq6p4Li3uoXY5QzVHGTZGh2u2dYKKyWKYbYTPQY5vx"

[workspace]
types = "target/types"

[surfpool]
startup_wait = 5000
log_level = "info"
block_production_mode = "clock"
